version: '3'

services: # the different images that will be running as containers
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=len_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=134340

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: /Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=len_db
      - DB_USER=dbuser
      - DB_PASS=134340
    ports:
      - "8000:8000"
    volumes:
      - ./:/len_back
    depends_on:
      - db
