version: '3'

services:
  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ms.beliv.ever@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 134340
    ports:
      - "5050:80"

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=len_db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=134340
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: /Dockerfile
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=len_db
      - DB_USER=dbuser
      - DB_PASS=134340
      - DB_PORT=5432
    ports:
      - "8000:8000"
    volumes:
      - ./:/len_back
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
