# Generated by Django 4.2.7 on 2023-12-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('next_date', models.DateField(verbose_name='Дата следующего занятия')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='ClassTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('definition', models.CharField(max_length=200)),
                ('start_cost', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Тип занятий',
                'verbose_name_plural': 'Типы занятий',
                'db_table': 'class_types',
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('fcs', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='ClientStatuses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
                'db_table': 'client_statuses',
            },
        ),
        migrations.CreateModel(
            name='ClientTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'Тип клиента',
                'verbose_name_plural': 'Типы клиентов',
                'db_table': 'client_types',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=40, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('ban_on_spam', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.clients')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='ContactsTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип контактов',
                'verbose_name_plural': 'Типы контактов',
                'db_table': 'contacts_types',
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clients')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.contacts')),
                ('guest_class', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='admin_app.classes')),
            ],
            options={
                'verbose_name': 'Гость',
                'verbose_name_plural': 'Гости',
                'db_table': 'guests',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='client_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clientstatuses'),
        ),
        migrations.AddField(
            model_name='clients',
            name='client_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clienttypes'),
        ),
        migrations.AddField(
            model_name='clients',
            name='contacts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.contacts'),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.classtypes', verbose_name='Тип занятия'),
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField()),
                ('receiving_date', models.DateField()),
                ('cost', models.IntegerField()),
                ('cost_used', models.IntegerField()),
                ('comment', models.CharField(max_length=400)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.classtypes')),
                ('client_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.clients')),
                ('client_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clients')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'db_table': 'certificates',
            },
        ),
        migrations.CreateModel(
            name='ClientsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.clients')),
                ('client_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clients')),
            ],
            options={
                'verbose_name': 'Группа клиентов',
                'verbose_name_plural': 'Группы клиентов',
                'db_table': 'clients_group',
                'unique_together': {('client_group', 'client')},
            },
        ),
        migrations.CreateModel(
            name='ClientsContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.clients')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.contacts')),
                ('contacts_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.contactstypes', verbose_name='Тип контактного лица')),
            ],
            options={
                'verbose_name': 'Контактные данные клиентов',
                'verbose_name_plural': 'Контактные данные клиентов',
                'db_table': 'clients_contacts',
                'unique_together': {('contacts', 'client')},
            },
        ),
    ]
