# Generated by Django 4.2.7 on 2023-12-08 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Тип фото',
                'verbose_name_plural': 'Типы фото',
                'db_table': 'photo_types',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_cost', models.IntegerField()),
                ('definition', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Тип изделия',
                'verbose_name_plural': 'Типы изделий',
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='ReadyStates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('comment', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Состояние готовности',
                'verbose_name_plural': 'Состояния готовности',
                'db_table': 'ready_states',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('definition', models.CharField(max_length=400)),
                ('cost', models.IntegerField()),
                ('first_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.classes')),
                ('product_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.producttypes')),
                ('ready_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.readystates')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductPhotos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=400)),
                ('photo_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.phototypes')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.products')),
                ('product_class', models.ForeignKey(db_column='class_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.classes')),
            ],
            options={
                'verbose_name': 'Фото изделия',
                'verbose_name_plural': 'Фото изделий',
                'db_table': 'product_photos',
            },
        ),
    ]
