# Generated by Django 4.2.7 on 2023-12-01 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_alter_contacts_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='contacts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.contacts'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.clients'),
            preserve_default=False,
        ),
    ]
