# Generated by Django 4.2.7 on 2024-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_phototypes_producttypes_readystates_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientstatuses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
