# Generated by Django 4.2.7 on 2023-12-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_contacts_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='comment',
            field=models.CharField(default=' ', max_length=500, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='contacts',
            field=models.ForeignKey(default='null', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='admin_app.contacts'),
        ),
    ]
