# Generated by Django 4.2.7 on 2024-03-11 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textures_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodels',
            name='path',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('glb', 'obj'))]),
        ),
    ]
